# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=luci-app-cowbping
LUCI_PKGARCH:=all
PKG_VERSION=v1.6
PKG_RELEASE:=v1.6-202105025

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature